stages:
  - deploy

deploy:
  stage: deploy
  script:
    - 'curl --header "Job-Token: z1FzU2dDFkhrxFny1raB" --data branch=master "https://gitlab.05.ru/api/v4/projects/microservice/packages/composer"'
