stages:
  - deploy

deploy:
  stage: deploy
  script:
    - Invoke-WebRequest -uri "https://@gitlab.05.ru/api/v4/projects/39/packages/composer?job_token=DGfVXS3Gs22d18ui7kPL" -Method Post -Body @{branch='master'}
