stages:
  - deploy

deploy:
  stage: deploy
  script:
     - curl -sS --show-error --fail --data tag=init "https://__token__:${CI_JOB_TOKEN}@gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/composer"
